# images are built from local docker files
# run command: docker compose up

services:
  database:
    image: postgis/postgis:16-3.5-alpine
    container_name: crime_map_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crimemapdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./crimemapdb_dump.sql:/docker-entrypoint-initdb.d/crimemapdb_dump.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.2
    ports:
      - "6379"
    restart: unless-stopped

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./backend
      dockerfile: Web/Dockerfile
    container_name: crime_map_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ALLOWED_ORIGINS=http://client:3000,http://client:80,https://client:443,https://client:3000
      - CONNECTION_STRING=Host=database;Port=5432;Database=crimemapdb;Username=postgres;Password=postgres
      - REDIS_HOST=redis:6379
    depends_on:
      - database
      - redis
    ports:
      - "8080"
      - "8081"
     
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: ./frontend/myth-crime-mapping-client
      dockerfile: Dockerfile
    container_name: crime_map_client
    depends_on:
      - api
    ports:
      - "80:80"
